title: <p align="center"> Adrian Aluoch </p>

logo: "/images/adrianaluoch.png?raw=true"

description: |
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/adrianjuliusaluoch/">LinkedIn</a> |
  <a href="https://github.com/adrianjuliusaluoch">GitHub</a>
  </p>

  <p style="text-align: justify; hyphens: auto; margin-bottom: 8px;">
  I'm a data analyst with a strong foundation in statistics and programming.
  </p>

  <p style="text-align: justify; hyphens: auto; margin-top: 0;">
  My work focuses on building data pipelines, analyzing datasets, and developing machine learning models to extract meaningful insights from complex data.
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-145578661-1